-- Generated by nwg-displays on 2026-08-02 at 15:33:36. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "1906x864",
    scale = 1.33,
    mirror = "eDP-1"
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "1906x864",
    scale = 1.0,
    mirror = "eDP-1"
})
