-- Generated by nwg-displays on 2026-08-14 at 10:57:57. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "1906x864",
    scale = 1.3333,
    mirror = "eDP-1"
})
