#!/usr/bin/env python3
"""Render one ricing palette into each application's native theme format."""
import json
import os
import sys
from pathlib import Path


def config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def hex_to_rgba(value: str) -> str:
    return f"rgba({value[1:]}ff)"


def hex_to_rgb_args(value: str) -> str:
    raw = value[1:]
    return ",".join(raw[index:index + 2] for index in range(0, 6, 2))


def render(palette: dict[str, str], root: Path) -> None:
    css = "/* Generated by ricing/apply-theme.py. Do not edit. */\n" + "\n".join(
        f"@define-color {key.replace('_', '-')} {value};" for key, value in palette.items() if key != "name"
    ) + "\n"
    write(root / "waybar" / "colors.css", css)

    hypr = "-- Generated by ricing/apply-theme.py. Do not edit.\nreturn {\n" + "\n".join(
        [
            f'  active_border = "{hex_to_rgba(palette["primary"])}",',
            f'  inactive_border = "{hex_to_rgba(palette["outline"])}",',
        ]
    ) + "\n}\n"
    write(root / "hypr" / "modules" / "theme.lua", hypr)

    lock = "\n".join([
        "# Generated by ricing/apply-theme.py. Do not edit.", "$font = Noto Sans", "",
        "general {", "    hide_cursor = false", "}", "",
        "animations {", "    enabled = true", "    bezier = linear, 1, 1, 0, 0",
        "    animation = fadeIn, 1, 5, linear", "    animation = fadeOut, 1, 5, linear",
        "    animation = inputFieldDots, 1, 2, linear", "}", "",
        "background {", "    monitor =", f"    color = rgb({hex_to_rgb_args(palette['background'])})",
        "    path = $HOME/.local/state/ricing/current-wallpaper", "    blur_passes = 1",
        "    brightness = 0.88", "    contrast = 1.00", "}", "",
        "input-field {", "    monitor =", "    size = 26%, 5.5%", "    outline_thickness = 4",
        f"    inner_color = rgba({palette['text'][1:]}cc)",
        f"    outer_color = rgba({palette['primary'][1:]}ff)",
        f"    check_color = rgba({palette['primary'][1:]}ee)",
        f"    fail_color = rgba({palette['error'][1:]}ee)",
        f"    font_color = rgb({hex_to_rgb_args(palette['text'])})", "    fade_on_empty = false", "    rounding = 20",
        "    font_family = $font", "    placeholder_text = Unlock", "    fail_text = $PAMFAIL",
        "    dots_spacing = 0.3", "    position = 0, 0", "    halign = center", "    valign = center", "}", "",
        "label {", "    monitor =", "    text = $TIME", "    font_size = 56", "    font_family = $font",
        f"    color = rgb({hex_to_rgb_args(palette['text'])})", "    position = 0, 140", "    halign = center", "    valign = center", "}", "",
        "label {", "    monitor =", "    text = cmd[update:60000] date +\"%A, %d %B %Y\"",
        "    font_size = 18", "    font_family = $font", f"    color = rgb({hex_to_rgb_args(palette['secondary'])})",
        "    position = 0, 214", "    halign = center", "    valign = center", "}", "",
    ])
    write(root / "hypr" / "hyprlock.conf", lock)

    kitty = "# Generated by ricing/apply-theme.py. Do not edit.\n" + "\n".join(
        [
            f"background {palette['surface']}",
            f"foreground {palette['text']}",
            f"selection_background {palette['outline']}",
            f"selection_foreground {palette['text']}",
            f"cursor {palette['primary']}",
            f"cursor_text_color {palette['background']}",
            f"active_tab_background {palette['primary']}",
            f"active_tab_foreground {palette['background']}",
            f"inactive_tab_background {palette['surface_high']}",
            f"inactive_tab_foreground {palette['text']}",
            f"tab_bar_background {palette['surface_low']}",
        ]
    ) + "\n"
    write(root / "kitty" / "theme.conf", kitty)

    starship = "\n".join([
        "# Generated by ricing/apply-theme.py. Do not edit.",
        'format = """$directory$git_branch$git_status$nodejs$python$rust$golang$cmd_duration\\n$character"""',
        "add_newline = true",
        "",
        "[directory]",
        f'style = "bold {palette["primary"]}"',
        "truncation_length = 4",
        "",
        "[git_branch]",
        f'style = "bold {palette["secondary"]}"',
        'symbol = " "',
        "",
        "[git_status]",
        f'style = "bold {palette["warning"]}"',
        "",
        "[nodejs]",
        f'style = "{palette["success"]}"',
        'symbol = " "',
        "",
        "[python]",
        f'style = "{palette["warning"]}"',
        'symbol = " "',
        "",
        "[rust]",
        f'style = "{palette["error"]}"',
        'symbol = "󱘗 "',
        "",
        "[golang]",
        f'style = "{palette["primary"]}"',
        'symbol = " "',
        "",
        "[cmd_duration]",
        f'style = "{palette["text_dim"]}"',
        "min_time = 500",
        "",
        "[character]",
        f'success_symbol = "[❯]({palette["primary"]})"',
        f'error_symbol = "[❯]({palette["error"]})"',
        "",
    ])
    write(root / "starship.toml", starship)

    codium = {
        "C_Cpp.intelliSenseEngine": "disabled",
        "workbench.colorTheme": "Default Dark Modern",
        "workbench.colorCustomizations": {
            "editor.background": palette["surface"],
            "editorGutter.background": palette["surface"],
            "sideBar.background": palette["surface_low"],
            "sideBarSectionHeader.background": palette["surface_low"],
            "activityBar.background": palette["surface_low"],
            "titleBar.activeBackground": palette["surface_low"],
            "titleBar.inactiveBackground": palette["surface_low"],
            "tab.activeBackground": palette["surface"],
            "tab.inactiveBackground": palette["surface_low"],
            "editorGroupHeader.tabsBackground": palette["surface_low"],
            "panel.background": palette["surface_low"],
            "terminal.background": palette["surface"],
            "list.hoverBackground": palette["surface_high"],
            "list.activeSelectionBackground": palette["surface_highest"],
        },
        "editor.minimap.enabled": False,
        "workbench.editor.showTabs": "single",
        "breadcrumbs.enabled": False,
        "terminal.integrated.cursorWidth": 2,
        "editor.smoothScrolling": True,
        "editor.cursorSmoothCaretAnimation": "on",
        "workbench.list.smoothScrolling": True,
        "terminal.integrated.smoothScrolling": True,
        "workbench.activityBar.location": "hidden",
        "workbench.statusBar.visible": False,
        "workbench.tips.enabled": False,
        "editor.scrollbar.horizontal": "hidden",
        "editor.scrollbar.vertical": "hidden",
        "editor.scrollbar.horizontalScrollbarSize": 0,
        "editor.scrollbar.verticalScrollbarSize": 0,
        "editor.overviewRulerLanes": 0,
        "editor.overviewRulerBorder": False,
        "editor.hideCursorInOverviewRuler": True,
        "window.menuBarVisibility": "hidden",
        "window.enableMenuBarMnemonics": False,
        "window.customMenuBarAltFocus": False,
        "telemetry.feedback.enabled": False,
        "workbench.notifications.showInTitleBar": False,
        "update.titleBar": False,
        "window.customTitleBarVisibility": "never",
        "window.titleBarStyle": "native",
        "editor.fontFamily": "'JetBrainsMono Nerd Font Mono', monospace",
        "editor.padding.top": 20,
        "editor.padding.bottom": 100,
        "editor.scrollBeyondLastLine": True,
        "editor.cursorSurroundingLines": 8,
        "editor.cursorSurroundingLinesStyle": "all",
        "editor.stickyScroll.enabled": False,
        "editor.unicodeHighlight.includeStrings": False,
    }
    write(root / "VSCodium" / "User" / "settings.json", json.dumps(codium, indent=2) + "\n")

    zsh = "\n".join([
        "# Generated by ricing/apply-theme.py. Do not edit.",
        f"ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg={palette['text_dim']}'",
        "typeset -gA ZSH_HIGHLIGHT_STYLES",
        f"ZSH_HIGHLIGHT_STYLES[command]='fg={palette['primary']},bold'",
        f"ZSH_HIGHLIGHT_STYLES[builtin]='fg={palette['secondary']},bold'",
        f"ZSH_HIGHLIGHT_STYLES[function]='fg={palette['secondary']}'",
        f"ZSH_HIGHLIGHT_STYLES[alias]='fg={palette['primary']},bold'",
        f"ZSH_HIGHLIGHT_STYLES[path]='fg={palette['text']},underline'",
        f"ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={palette['error']},bold'",
        f"ZSH_HIGHLIGHT_STYLES[globbing]='fg={palette['warning']}'",
        "",
    ])
    write(root / "ricing" / "generated" / "zsh-theme.zsh", zsh)

    swaync = "/* Generated by ricing/apply-theme.py. Do not edit. */\n:root {\n" + "\n".join(
        f"  --{key.replace('_', '-')}: {value};" for key, value in palette.items() if key != "name"
    ) + "\n}\n"
    write(root / "swaync" / "theme.css", swaync)


def main() -> None:
    root = config_home()
    theme = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "ricing" / "themes" / "ocean.json"
    with theme.open(encoding="utf-8") as file:
        palette = json.load(file)
    required = {"background", "surface", "surface_low", "surface_high", "surface_highest", "outline", "text", "text_muted", "text_dim", "primary", "primary_container", "secondary", "success", "warning", "error"}
    missing = required - palette.keys()
    if missing:
        raise SystemExit(f"Theme is missing: {', '.join(sorted(missing))}")
    render(palette, root)
    print(f"Applied theme: {palette.get('name', theme.stem)}")


if __name__ == "__main__":
    main()
